const regionOptions = [
	{ value: '', label: 'Моля изберете регион.' },
	{ value: '588', label: 'Blagoevgrad' },
	{ value: '589', label: 'Burgas' },
	{ value: '595', label: 'Dobrich' },
	{ value: '594', label: 'Gabrovo' },
	{ value: '613', label: 'Haskovo' },
	{ value: '596', label: 'Kardzhali' },
	{ value: '597', label: 'Kyustendil' },
	{ value: '598', label: 'Lovech' },
	{ value: '599', label: 'Montana' },
	{ value: '600', label: 'Pazardzhik' },
	{ value: '601', label: 'Pernik' },
	{ value: '602', label: 'Pleven' },
	{ value: '603', label: 'Plovdiv' },
	{ value: '604', label: 'Razgrad' },
	{ value: '605', label: 'Ruse' },
	{ value: '614', label: 'Shumen' },
	{ value: '606', label: 'Silistra' },
	{ value: '607', label: 'Sliven' },
	{ value: '608', label: 'Smolyan' },
	{ value: '609', label: 'Sofia City' },
	{ value: '610', label: 'Sofia Province' },
	{ value: '611', label: 'Stara Zagora' },
	{ value: '612', label: 'Targovishte' },
	{ value: '590', label: 'Varna' },
	{ value: '591', label: 'Veliko Tarnovo' },
	{ value: '592', label: 'Vidin' },
	{ value: '593', label: 'Vratsa' },
	{ value: '615', label: 'Yambol' },
]

const countryOptions = [
	{ value: 'AU', label: 'Австралия' },
	{ value: 'AT', label: 'Австрия' },
	{ value: 'AL', label: 'Албания' },
	{ value: 'AI', label: 'Ангуила' },
	{ value: 'AD', label: 'Андора' },
	{ value: 'AR', label: 'Аржентина' },
	{ value: 'AW', label: 'Аруба' },
	{ value: 'BE', label: 'Белгия' },
	{ value: 'BM', label: 'Бермудски острови' },
	{ value: 'BA', label: 'Босна и Херцеговина' },
	{ value: 'BR', label: 'Бразилия' },
	{ value: 'VN', label: 'Виетнам' },
	{ value: 'GM', label: 'Гамбия' },
	{ value: 'GP', label: 'Гваделупа' },
	{ value: 'GN', label: 'Гвинея' },
	{ value: 'DE', label: 'Германия' },
	{ value: 'GI', label: 'Гибралтар' },
	{ value: 'GR', label: 'Гърция' },
	{ value: 'DK', label: 'Дания' },
	{ value: 'JE', label: 'Джърси' },
	{ value: 'EG', label: 'Египет' },
	{ value: 'ER', label: 'Еритрея' },
	{ value: 'EE', label: 'Естония' },
	{ value: 'IL', label: 'Израел' },
	{ value: 'IN', label: 'Индия' },
	{ value: 'IR', label: 'Иран' },
	{ value: 'IE', label: 'Ирландия' },
	{ value: 'IS', label: 'Исландия' },
	{ value: 'ES', label: 'Испания' },
	{ value: 'IT', label: 'Италия' },
	{ value: 'KZ', label: 'Казахстан' },
	{ value: 'KY', label: 'Кайманови острови' },
	{ value: 'CA', label: 'Канада' },
	{ value: 'QA', label: 'Катар' },
	{ value: 'CY', label: 'Кипър' },
	{ value: 'CN', label: 'Китай' },
	{ value: 'CO', label: 'Колумбия' },
	{ value: 'LV', label: 'Латвия' },
	{ value: 'LB', label: 'Ливан' },
	{ value: 'LT', label: 'Литва' },
	{ value: 'LI', label: 'Лихтенщайн' },
	{ value: 'LU', label: 'Люксембург' },
	{ value: 'YT', label: 'Майот' },
	{ value: 'MA', label: 'Мароко' },
	{ value: 'MQ', label: 'Мартиника' },
	{ value: 'MX', label: 'Мехико' },
	{ value: 'MD', label: 'Молдова' },
	{ value: 'MC', label: 'Монако' },
	{ value: 'MS', label: 'Монтсерат' },
	{ value: 'NL', label: 'Нидерландия' },
	{ value: 'NZ', label: 'Нова Зеландия' },
	{ value: 'NO', label: 'Норвегия' },
	{ value: 'AE', label: 'Обединени арабски емирства' },
	{ value: 'GB', label: 'Обединеното кралство' },
	{ value: 'PK', label: 'Пакистан' },
	{ value: 'PL', label: 'Полша' },
	{ value: 'PT', label: 'Португалия' },
	{ value: 'RE', label: 'Реюнион' },
	{ value: 'RO', label: 'Румъния' },
	{ value: 'SJ', label: 'Свалбард и Ян Майен' },
	{ value: 'SH', label: 'Света Елена' },
	{ value: 'PM', label: 'Сен Пиер и Микелон' },
	{ value: 'SK', label: 'Словакия' },
	{ value: 'SI', label: 'Словения' },
	{ value: 'US', label: 'Съединени щати' },
	{ value: 'RS', label: 'Сърбия' },
	{ value: 'TH', label: 'Тайланд' },
	{ value: 'TN', label: 'Тунис' },
	{ value: 'TR', label: 'Турция' },
	{ value: 'UA', label: 'Украйна' },
	{ value: 'HU', label: 'Унгария' },
	{ value: 'WF', label: 'Уолис и Футуна' },
	{ value: 'FI', label: 'Финландия' },
	{ value: 'FK', label: 'Фолкландски острови' },
	{ value: 'FR', label: 'Франция' },
	{ value: 'GF', label: 'Френска Гвиана' },
	{ value: 'PF', label: 'Френска Полинезия' },
	{ value: 'TF', label: 'Френски южни територии' },
	{ value: 'HR', label: 'Хърватия' },
	{ value: 'ME', label: 'Черна гора' },
	{ value: 'CZ', label: 'Чехия' },
	{ value: 'CL', label: 'Чили' },
	{ value: 'CH', label: 'Швейцария' },
	{ value: 'SE', label: 'Швеция' },
	{ value: 'ZA', label: 'Южна Африка' },
	{ value: 'JM', label: 'Ямайка' },
	{ value: 'JP', label: 'Япония' },
	{ value: 'BV', label: 'остров Буве' },
]

export const locationOptions = {
	countryOptions,
	regionOptions,
}
